server:
  port: 8080

spring:
  application:
    name: "gateway-server"
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: "user-service"
          uri: "lb://user-service"
          predicates:
            - "Path=/api/users/**"

        - id: "customer-service"
          uri: "lb://customer-service"
          predicates:
            - "Path=/api/customers/**"

        - id: "contract-service"
          uri: "lb://contract-service"
          predicates:
            - "Path=/api/contracts/**"

        - id: "plan-service"
          uri: "lb://plan-service"
          predicates:
            - "Path=/api/plans/**"

        - id: "billing-service"
          uri: "lb://billing-service"
          predicates:
            - "Path=/api/billings/**"

        - id: "support-service"
          uri: "lb://support-service"
          predicates:
            - "Path=/api/support/**"

        - id: "analytics-service"
          uri: "lb://analytics-service"
          predicates:
            - "Path=/api/analytics/**"

        - id: "notification-service"
          uri: "lb://notification-service"
          predicates:
            - "Path=/api/notifications/**"
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
