configurl: http://localhost:8070

spring:
  main:
    allow-bean-definition-overriding: true
  config:
    import: configserver:${configurl}
  application:
    name: "analyticsservice"
  cloud:
    config:
      profile: prod
      fail-fast: true
      uri: ${configurl}


