configurl: http://localhost:8070

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: "gatewayserver"
  cloud:
    config:
      profile: dev
      uri: ${configurl}
  config:
    import: optional:configserver:${configurl}