configurl: http://localhost:8070

spring:
  application:
    name: "notificationservice"
  cloud:
    config:
      profile: dev
      uri: ${configurl}
  config:
    import: optional:configserver:${configurl}