global:
  scrape_interval: 15s # Metriklerin her 15 saniyede bir toplanmasını sağlar.

scrape_configs:
  - job_name: 'prometheus' # Job to scrape Prometheus metrics
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: "analyticsservice"
    scrape_interval: 30s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8071"]
    basic_auth:
      username: "prometheus"
      password: "prometheus"