{
 "title": "Spring Boot Metrics",
 "tags": [
  "spring",
  "java"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(jvm_memory_used_bytes, application)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})",
     "legendFormat": "Heap Memory Used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"heap\"})",
     "legendFormat": "Heap Memory Committed"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[1m])",
     "legendFormat": "{{method}} {{uri}} - {{status}}"
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_usage * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_usage * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "JVM GC Collection Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "jvm_gc_pause_seconds_count", "legendFormat": "{{action}} - {{cause}}" }
   ]
  }
 ]
}