configurl: http://localhost:8070

spring:
  profiles:
    active: local
  config:
    import: configserver:${configurl}
  application:
    name: "customerservice"
  cloud:
    config:
      profile: local
      fail-fast: true
      uri: ${configurl}



