spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5435/customer
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    function:
      definition: emailNotification;smsNotification;pushNotification
    stream:
      defaultBinder: kafka
      bindings:
        emailNotification-out-0:
          destination: emailNotificationFunction-in-0
          content-type: application/json
          group: notification-group
        smsNotification-out-0:
          destination: smsNotificationFunction-in-0
          content-type: application/json
          group: notification-group
        pushNotification-out-0:
          destination: pushNotificationFunction-in-0
          content-type: application/json
          group: notification-group
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 8020

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# JWT Configuration
jwt:
  secret-key: very-secure-jwt-secret-key-used-for-signing-tokens-in-user-service
  expiration-ms: 86400000
  issuer: user-service
  token-prefix: "Bearer "
  header-string: Authorization
