apiVersion: v1
kind: ConfigMap
metadata:
  name: crm-system-config
  namespace: crm-system
data:
  SPRING_PROFILES_ACTIVE: "prod"
  CONFIGURL: "http://config-server:8070"
  SPRING_CLOUD_CONFIG_PROFILE: "prod"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8888/eureka"
  DOCKERHUB_USERNAME: "batuce"
