apiVersion: v1
kind: Service
metadata:
  name: discovery-server-lb
  namespace: crm-system
spec:
  type: LoadBalancer
  selector:
    app: discovery-server
  ports:
    - port: 8888
      targetPort: 8888
