configurl: http://localhost:8070

spring:
  application:
    name: "planservice"
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  cloud:
    config:
      uri: ${configurl}
  config:
    import: optional:configserver:${configurl}