configurl: http://localhost:8070

spring:
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  config:
    import: configserver:${configurl}
  application:
    name: "userservice"
  cloud:
    config:
      profile: local
      fail-fast: true
      uri: ${configurl}


