---
# User Service
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: crm-system
spec:
  selector:
    app: user-service
  ports:
    - port: 8010
      targetPort: 8010
      nodePort: 30010
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8010
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-user:5432/user
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8888/eureka
            - name: CONFIGURL
              value: http://config-server:8070
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8070
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "false"
            - name: SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL
              value: "1000"
            - name: SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS
              value: "6"
            - name: SPRING_CLOUD_CONFIG_RETRY_MAX_INTERVAL
              value: "2000"
            - name: SPRING_CLOUD_CONFIG_RETRY_MULTIPLIER
              value: "1.1"
            - name: SPRING_APPLICATION_NAME
              value: userservice
          resources:
            requests:
              memory: "512Mi"
---
# Customer Service
apiVersion: v1
kind: Service
metadata:
  name: customer-service
  namespace: crm-system
spec:
  selector:
    app: customer-service
  ports:
    - port: 8020
      targetPort: 8020
      nodePort: 30020
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: customer-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8020
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-customer:5432/customer
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8888/eureka
            - name: CONFIGURL
              value: http://config-server:8070
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8070
          resources:
            requests:
              memory: "512Mi"
---
# Billing Service
apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: crm-system
spec:
  selector:
    app: billing-service
  ports:
    - port: 8050
      targetPort: 8050
      nodePort: 30050
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
        - name: billing-service
          image: billing-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8050
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-billing:5432/billing
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8888/eureka
            - name: CONFIGURL
              value: http://config-server:8070
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8070
          resources:
            requests:
              memory: "512Mi"
---
# Analytics Service
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: crm-system
spec:
  selector:
    app: analytics-service
  ports:
    - port: 8071
      targetPort: 8071
      nodePort: 30071
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: analytics-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8071
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-analytics:5432/analytics
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8888/eureka
            - name: CONFIGURL
              value: http://config-server:8070
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8070
            - name: SPRING_APPLICATION_NAME
              value: analyticsservice
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "false"
          resources:
            requests:
              memory: "512Mi"
---
# Gateway Server Service
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
  namespace: crm-system
spec:
  selector:
    app: gateway-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
---
# Gateway Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server
          image: gateway-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8888/eureka
            - name: CONFIGURL
              value: http://config-server:8070
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8070
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: SPRING_CLOUD_SERVICE_REGISTRY_AUTO_REGISTRATION_ENABLED
              value: "true"
            - name: SPRING_APPLICATION_NAME
              value: gatewayserver
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "false"
            - name: SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL
              value: "1000"
            - name: SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS
              value: "6"
            - name: SPRING_CLOUD_CONFIG_RETRY_MAX_INTERVAL
              value: "2000"
            - name: SPRING_CLOUD_CONFIG_RETRY_MULTIPLIER
              value: "1.1"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
# Contract Service
apiVersion: v1
kind: Service
metadata:
  name: contract-service
  namespace: crm-system
spec:
  selector:
    app: contract-service
  ports:
    - port: 8030
      targetPort: 8030
      nodePort: 30030
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contract-service
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contract-service
  template:
    metadata:
      labels:
        app: contract-service
    spec:
      containers:
        - name: contract-service
          image: contract-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8030
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-contract:5432/contract
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8888/eureka
            - name: CONFIGURL
              value: http://config-server:8070
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8070
            - name: SPRING_APPLICATION_NAME
              value: contractservice
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "false"
          resources:
            requests:
              memory: "512Mi"
---
# Plan Service
apiVersion: v1
kind: Service
metadata:
  name: plan-service
  namespace: crm-system
spec:
  selector:
    app: plan-service
  ports:
    - port: 8040
      targetPort: 8040
      nodePort: 30040
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plan-service
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plan-service
  template:
    metadata:
      labels:
        app: plan-service
    spec:
      containers:
        - name: plan-service
          image: plan-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8040
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-plan:5432/plan
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8888/eureka
            - name: CONFIGURL
              value: http://config-server:8070
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8070
            - name: SPRING_APPLICATION_NAME
              value: planservice
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "false"
          resources:
            requests:
              memory: "512Mi"
---
# Notification Service
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: crm-system
spec:
  selector:
    app: notification-service
  ports:
    - port: 8060
      targetPort: 8060
      nodePort: 30060
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8060
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-notification:5432/notification
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8888/eureka
            - name: CONFIGURL
              value: http://config-server:8070
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8070
            - name: SPRING_APPLICATION_NAME
              value: notificationservice
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "false"
          resources:
            requests:
              memory: "512Mi"
---
# Customer Support Service
apiVersion: v1
kind: Service
metadata:
  name: customer-support-service
  namespace: crm-system
spec:
  selector:
    app: customer-support-service
  ports:
    - port: 8070
      targetPort: 8070
      nodePort: 30070
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-support-service
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-support-service
  template:
    metadata:
      labels:
        app: customer-support-service
    spec:
      containers:
        - name: customer-support-service
          image: customer-support-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8070
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-customer-support:5432/customersupport
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8888/eureka
            - name: CONFIGURL
              value: http://config-server:8070
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8070
            - name: SPRING_APPLICATION_NAME
              value: customersupportservice
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "false"
          resources:
            requests:
              memory: "512Mi"
---
# Config Server Service
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: crm-system
spec:
  selector:
    app: config-server
  ports:
    - port: 8070
      targetPort: 8070
      nodePort: 30100
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: config-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8070
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          resources:
            requests:
              memory: "512Mi"
---
# Discovery Server Service
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: crm-system
spec:
  selector:
    app: discovery-server
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30888
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: discovery-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          resources:
            requests:
              memory: "512Mi"
