configurl: http://localhost:8070

spring:
  config:
    import: configserver:${configurl}
  application:
    name: "billingservice"
  cloud:
    config:
      profile: prod
      fail-fast: true
      uri: ${configurl}


