spring:
  application:
    name: "discovery-server"

server:
  port: 8888

eureka:
  instance:
    hostname: "localhost"
  client:
    serviceUrl:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: false
    fetch-registry: false