{
 "title": "CRM Analytics Dashboard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "User Registrations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "user_registrations_total", "legendFormat": "User Registrations" }
   ]
  },
  {
   "title": "Toplam login sayısı",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(user_login_duration_seconds_count{application=\"analytics-service\"}[1h]))",
     "legendFormat": "Customer Registrations"
    }
   ]
  },
  {
   "title": "customer count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "customer_registrations_total{application=\"analytics-service\"}",
     "legendFormat": "Tickets Created"
    }
   ]
  },
  {
   "title": "Ortalama login süresi (saniye)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(user_login_duration_seconds_sum{application=\"analytics-service\"}[5m])) / sum(rate(user_login_duration_seconds_count{application=\"analytics-service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "create total ticket count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "tickets_total{application=\"analytics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Son 1 saatteki en uzun login süresi",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(user_login_duration_seconds_max{application=\"analytics-service\"}[1h])",
     "legendFormat": "Login Duration (ms)"
    }
   ]
  },
  {
   "title": "Update ticket count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "tickets_updated_total{application=\"analytics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bill Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "bill_total_count_total{application=\"analytics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Closed Ticket Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "tickets_closed_total{application=\"analytics-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}