---
# Config Server Service
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: crm-system
spec:
  selector:
    app: config-server
  ports:
    - port: 8070
      targetPort: 8070
      nodePort: 30070
  type: NodePort
---
# Config Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: config-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8070
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "git,prod"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: "https://github.com/melih-vardar/crm-microservices-turkcell-final-project-configs"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL
              value: "main"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_CLONE_ON_START
              value: "true"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS
              value: "."
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_TIMEOUT
              value: "10"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_FORCE_PULL
              value: "true"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_SKIP_SSL_VALIDATION
              value: "true"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
# Discovery Server Service
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: crm-system
spec:
  selector:
    app: discovery-server
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30888
  type: NodePort
---
# Discovery Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: discovery-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8888
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8888/eureka
            - name: CONFIGURL
              value: http://config-server:8070
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8070
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
# Gateway Server Service
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
  namespace: crm-system
spec:
  selector:
    app: gateway-server
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
---
# Gateway Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
  namespace: crm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server
          image: gateway-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8888/eureka
            - name: CONFIGURL
              value: http://config-server:8070
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-server:8070
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: SPRING_CLOUD_SERVICE_REGISTRY_AUTO_REGISTRATION_ENABLED
              value: "true"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
