spring:
  application:
    name: "configserver"
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/melih-vardar/crm-microservices-turkcell-final-project-configs.git"
          default-label: main
          clone-on-start: true
          skip-ssl-validation: true
          force-pull: true
          timeout: 10
          refresh-rate: 30
server:
  port: 8070

# Debug için log seviyesini artırma
logging:
  level:
    root: INFO
    org.springframework.cloud.config: DEBUG
    org.springframework.boot: INFO
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
