spring:
  application:
    name: "config-server"
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/melih-vardar/crm-microservices-turkcell-final-project-configs.git"
          default-label: main
          clone-on-start: true
          skip-ssl-validation: true
server:
  port: 8070

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always