name: Build and Deploy Microservices

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  DOCKERHUB_USERNAME: bothuany

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          [
            config-server,
            discovery-server,
            gateway-server,
            user-service,
            customer-service,
            billing-service,
            analytics-service,
            contract-service,
            plan-service,
            notification-service,
            customer-support-service,
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
            ${{ env.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ github.sha }}

  deploy-to-kubernetes:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Update Kubernetes manifests
        run: |
          # Replace placeholders with actual values
          find ./k8s -type f -name "*.yaml" -exec sed -i "s/\${DOCKERHUB_USERNAME}/${{ secrets.DOCKERHUB_USERNAME }}/g" {} \;

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/00-namespace.yaml
          kubectl apply -f k8s/01-configmaps.yaml
          kubectl apply -f k8s/02-storage.yaml
          kubectl apply -f k8s/03-databases.yaml
          kubectl apply -f k8s/04-kafka.yaml
          kubectl apply -f k8s/05-monitoring.yaml
          kubectl apply -f k8s/07-config-maps.yaml

          # Wait for infrastructure to be ready
          echo "Waiting for infrastructure components to be ready..."
          sleep 30

          # Deploy core services
          kubectl apply -f k8s/06-core-services.yaml

          # Wait for core services to be ready
          echo "Waiting for core services to be ready..."
          sleep 60

          # Deploy microservices
          kubectl apply -f k8s/08-microservices.yaml

          echo "Deployment completed"

      - name: Verify deployment
        run: |
          kubectl get all -n crm-system
          echo "Access your application at http://$(kubectl get ingress gateway-ingress -n crm-system -o jsonpath='{.status.loadBalancer.ingress[0].ip}')"
